version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
  redis:
    image: redis
    volumes:
      - ./tmp/redis:/data
    ports:
      - "6379:6379"
