default: &default
  adapter: postgresql
  username: postgres
  password: password
  host: 0.0.0.0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: meal_planner_development

test:
  <<: *default
  database: meal_planner_test
